// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound screenshot helper API (Developer 1).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SavePNG decodes a base64 PNG (optionally a `data:image/png;base64,...` URL)
 * produced by the Konva editor and writes it to a temp file, returning the
 * path. The editor then hands that path to ExportService.SaveAs /
 * ExportService.CopyToClipboard.
 */
export function SavePNG(pngBase64: string): $CancellablePromise<string> {
    return $Call.ByID(682279761, pngBase64);
}
