// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HotkeyService is the Wails-bound API the React Shortcuts panel calls. It is a
 * thin, cross-platform facade over the Manager (which owns the live LL hook) plus
 * settings.json persistence.
 * 
 * JS binding name: HotkeyService.*
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetShortcuts returns every configured action's current combo for the UI.
 */
export function GetShortcuts(): $CancellablePromise<$models.Shortcut[]> {
    return $Call.ByID(2331534736).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetShortcut restores action to its registered default, persists it, and
 * updates the live binding.
 */
export function ResetShortcut(action: string): $CancellablePromise<void> {
    return $Call.ByID(2253036404, action);
}

/**
 * SetShortcut validates sc, persists it to settings.json, then updates the live
 * hook binding (no reinstall — the hook reads the mutex-guarded binding list). It
 * returns a validation/persist error to the frontend, which surfaces it inline.
 */
export function SetShortcut(action: string, sc: $models.Shortcut): $CancellablePromise<void> {
    return $Call.ByID(2096590663, action, sc);
}

// Private type creation functions
const $$createType0 = $models.Shortcut.createFrom;
const $$createType1 = $Create.Array($$createType0);
