// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as HotkeyService from "./hotkeyservice.js";
export {
    HotkeyService
};

export {
    Shortcut
} from "./models.js";
