// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Shortcut is the binding-friendly wire shape for the frontend. Key is a STRING
 * ("S") so the TS side stays clean; it converts to/from the internal rune Binding
 * in Go. JSON tags keep the generated TS field names stable + lowercase.
 * 
 * JS binding name: HotkeyService.* (see HotkeyService below).
 */
export class Shortcut {
    /**
     * stable id, e.g. "overlay"
     */
    "action": string;

    /**
     * human label, e.g. "Open capture overlay"
     */
    "label": string;
    "ctrl": boolean;
    "shift": boolean;
    "alt": boolean;
    "win": boolean;

    /**
     * single uppercase char "A".."Z" or "0".."9"
     */
    "key": string;

    /** Creates a new Shortcut instance. */
    constructor($$source: Partial<Shortcut> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("ctrl" in $$source)) {
            this["ctrl"] = false;
        }
        if (!("shift" in $$source)) {
            this["shift"] = false;
        }
        if (!("alt" in $$source)) {
            this["alt"] = false;
        }
        if (!("win" in $$source)) {
            this["win"] = false;
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Shortcut instance from a string or object.
     */
    static createFrom($$source: any = {}): Shortcut {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Shortcut($$parsedSource as Partial<Shortcut>);
    }
}
