// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "../capture/models.js";

/**
 * MonitorSession is the per-overlay-window payload. One is produced per monitor
 * by BeginSession; each is also embedded in its window's URL so the front end
 * can render WITHOUT a binding round-trip on first paint.
 */
export class MonitorSession {
    /**
     * == kbinani idx == ScreenInfo.ID == ddagrab output_idx
     */
    "monitorId": number;

    /**
     * StillURL is served by ShotMiddleware, e.g. "/__shot/0".
     */
    "stillUrl": string;

    /**
     * Monitor geometry in VIRTUAL-DESKTOP PHYSICAL px (origin = primary top-left;
     * monitors left/above carry NEGATIVE X/Y).
     */
    "x": number;
    "y": number;
    "w": number;
    "h": number;

    /**
     * Scale is the monitor DPI scale (CSS px * scale = physical px).
     */
    "scale": number;

    /**
     * IsPrimary marks the single interactive (crop + pill) window.
     */
    "isPrimary": boolean;

    /**
     * Crop is MONITOR-LOCAL PHYSICAL px; zero-value {0,0,0,0} when not primary
     * or when there is no restored/default crop.
     */
    "crop": capture$0.Rect;

    /** Creates a new MonitorSession instance. */
    constructor($$source: Partial<MonitorSession> = {}) {
        if (!("monitorId" in $$source)) {
            this["monitorId"] = 0;
        }
        if (!("stillUrl" in $$source)) {
            this["stillUrl"] = "";
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            this["h"] = 0;
        }
        if (!("scale" in $$source)) {
            this["scale"] = 0;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("crop" in $$source)) {
            this["crop"] = (new capture$0.Rect());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorSession instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorSession {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("crop" in $$parsedSource) {
            $$parsedSource["crop"] = $$createField8_0($$parsedSource["crop"]);
        }
        return new MonitorSession($$parsedSource as Partial<MonitorSession>);
    }
}

// Private type creation functions
const $$createType0 = capture$0.Rect.createFrom;
