// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "../capture/models.js";

/**
 * MonitorSession is the per-overlay-window payload. One is produced per monitor
 * by BeginSession; each is also embedded in its window's URL so the front end
 * can render WITHOUT a binding round-trip on first paint.
 */
export class MonitorSession {
    /**
     * == kbinani idx == ScreenInfo.ID == ddagrab output_idx
     */
    "monitorId": number;

    /**
     * StillURL is served by ShotMiddleware, e.g. "/__shot/0".
     */
    "stillUrl": string;

    /**
     * Monitor geometry in VIRTUAL-DESKTOP PHYSICAL px (origin = primary top-left;
     * monitors left/above carry NEGATIVE X/Y).
     */
    "x": number;
    "y": number;
    "w": number;
    "h": number;

    /**
     * Scale is the monitor DPI scale (CSS px * scale = physical px).
     */
    "scale": number;

    /**
     * IsPrimary marks the single interactive (crop + pill) window.
     */
    "isPrimary": boolean;

    /**
     * Crop is MONITOR-LOCAL PHYSICAL px; zero-value {0,0,0,0} when not primary
     * or when there is no restored/default crop. LEGACY: the shared-crop overlay
     * seeds from Region instead; Crop is retained for older callers/tests.
     */
    "crop": capture$0.Rect;

    /**
     * Region is the SHARED crop in VIRTUAL-DESKTOP PHYSICAL px (origin = primary
     * top-left; may be negative; MAY straddle monitors). EVERY window receives the
     * SAME Region and renders its own slice of it — this is the single source of
     * truth for the cross-monitor selection. Seeded from persisted state / a
     * centered default by buildSessionPayloads.
     */
    "region": capture$0.Rect;

    /**
     * Freeze tells React how this engage was rendered: true => paint the frozen
     * StillURL backdrop (classic); false => no backdrop, the transparent window
     * shows the LIVE desktop and a screenshot grabs live pixels at Capture.
     */
    "freeze": boolean;

    /** Creates a new MonitorSession instance. */
    constructor($$source: Partial<MonitorSession> = {}) {
        if (!("monitorId" in $$source)) {
            this["monitorId"] = 0;
        }
        if (!("stillUrl" in $$source)) {
            this["stillUrl"] = "";
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            this["h"] = 0;
        }
        if (!("scale" in $$source)) {
            this["scale"] = 0;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("crop" in $$source)) {
            this["crop"] = (new capture$0.Rect());
        }
        if (!("region" in $$source)) {
            this["region"] = (new capture$0.Rect());
        }
        if (!("freeze" in $$source)) {
            this["freeze"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorSession instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorSession {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("crop" in $$parsedSource) {
            $$parsedSource["crop"] = $$createField8_0($$parsedSource["crop"]);
        }
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField9_0($$parsedSource["region"]);
        }
        return new MonitorSession($$parsedSource as Partial<MonitorSession>);
    }
}

/**
 * OverlayEditPayload is the overlay:edit event payload (Go->JS). It is emitted by
 * EnterEdit to the SAME overlay window (no separate editor window) so React can
 * load the served crop PNG as the editor base image, size the Konva stage to the
 * crop's CSS rect, position it exactly where the bright region was on screen, and
 * morph the dock into the annotation toolbar. React filters by MonitorID == its
 * URL ?mon=, so a non-target window ignores it and stays dimmed.
 */
export class OverlayEditPayload {
    "monitorId": number;

    /**
     * served crop PNG, e.g. "/__file/<base>"
     */
    "cropUrl": string;

    /**
     * region left in CSS px within the window
     */
    "cssLeft": number;

    /**
     * region top  in CSS px
     */
    "cssTop": number;

    /**
     * region width  in CSS px = stage width
     */
    "cssW": number;

    /**
     * region height in CSS px = stage height
     */
    "cssH": number;

    /**
     * monitor-local physical crop (Save provenance)
     */
    "sub": capture$0.Rect;

    /** Creates a new OverlayEditPayload instance. */
    constructor($$source: Partial<OverlayEditPayload> = {}) {
        if (!("monitorId" in $$source)) {
            this["monitorId"] = 0;
        }
        if (!("cropUrl" in $$source)) {
            this["cropUrl"] = "";
        }
        if (!("cssLeft" in $$source)) {
            this["cssLeft"] = 0;
        }
        if (!("cssTop" in $$source)) {
            this["cssTop"] = 0;
        }
        if (!("cssW" in $$source)) {
            this["cssW"] = 0;
        }
        if (!("cssH" in $$source)) {
            this["cssH"] = 0;
        }
        if (!("sub" in $$source)) {
            this["sub"] = (new capture$0.Rect());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverlayEditPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): OverlayEditPayload {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sub" in $$parsedSource) {
            $$parsedSource["sub"] = $$createField6_0($$parsedSource["sub"]);
        }
        return new OverlayEditPayload($$parsedSource as Partial<OverlayEditPayload>);
    }
}

// Private type creation functions
const $$createType0 = capture$0.Rect.createFrom;
