// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OverlayService is the Wails-bound overlay/coordination API (JS: OverlayService.*).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "../capture/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginSession is the launch entrypoint. It enumerates screens, freezes EVERY
 * monitor's still BEFORE any overlay window is shown, restores the persisted
 * primary crop (or a centered default), opens one window per monitor, and
 * returns the per-monitor session payloads. Returning []MonitorSession also lets
 * the binding generator emit the MonitorSession TS type.
 */
export function BeginSession(): $CancellablePromise<$models.MonitorSession[]> {
    return $Call.ByID(142875180).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Cancel dismisses ALL overlay windows then re-opens the dev Hub so editors stay
 * reachable during Phase 0, and notifies the UI.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(63226937);
}

/**
 * Commit is a thin compatibility shim kept so existing bindings/tests don't
 * break. For screenshots it routes through the frozen-still crop using req.Rect
 * as the contract Rect and deriving the monitor-local sub-rect from the owning
 * screen's origin. New code should call CommitScreenshot directly. Video is
 * delegated to StartRecording (the overlay records the live region).
 */
export function Commit(req: capture$0.CaptureRequest): $CancellablePromise<capture$0.CaptureResult> {
    return $Call.ByID(3467496406, req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CommitScreenshot is THE screenshot path. It crops the FROZEN still for
 * monitorID (NEVER a live re-capture), dismisses the overlay, emits capture:done,
 * and opens the editor. rect is the contract Rect (virtual-desktop physical px)
 * carried in the result; sub is the monitor-local physical crop region applied to
 * the frozen PNG. Both are computed by the front end via CropToPhysical.
 */
export function CommitScreenshot(monitorID: number, rect: capture$0.Rect, sub: capture$0.Rect, copyOnCommit: boolean): $CancellablePromise<capture$0.CaptureResult> {
    return $Call.ByID(2125643298, monitorID, rect, sub, copyOnCommit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DismissSession closes ALL overlay windows (via the kept handles), clears the
 * session state, and best-effort deletes the temp frozen PNGs. Emitting
 * overlay:dismiss alone does NOT destroy the native windows — Close() does.
 */
export function DismissSession(): $CancellablePromise<void> {
    return $Call.ByID(3873625871);
}

/**
 * ListScreens is THE single source of truth for monitor enumeration that both
 * halves trust. ID == kbinani idx == ddagrab output_idx.
 * 
 * It enumerates via capture.EnumDisplays (kbinani; Windows-only behind a build
 * tag) for physical, virtual-desktop-origin bounds, then enriches ScaleFactor +
 * IsPrimary from the Wails ScreenManager matched by PhysicalBounds origin. The
 * slice is never sorted or deduped so the index stays == output_idx.
 */
export function ListScreens(): $CancellablePromise<capture$0.ScreenInfo[]> {
    return $Call.ByID(3187571944).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SaveCrop persists the monitor-local PHYSICAL-px crop for monitorID. Called by
 * the front end on crop drag-end (debounced) and again inside CommitScreenshot
 * before dismiss.
 */
export function SaveCrop(monitorID: number, sub: capture$0.Rect): $CancellablePromise<void> {
    return $Call.ByID(803232484, monitorID, sub);
}

/**
 * SetActiveMonitor broadcasts which monitor owns the capture selection. Called
 * by an overlay window when the user clicks into it; all windows (including
 * the caller) receive the event and show/hide their selection chrome.
 */
export function SetActiveMonitor(monitorID: number): $CancellablePromise<void> {
    return $Call.ByID(1008328671, monitorID);
}

/**
 * StartRecording dismisses the overlay FIRST (so ffmpeg records the live region,
 * not the dim overlays), THEN begins recording, THEN opens the recording pill
 * (timer + Stop). req.Rect is the virtual-desktop physical Rect the front end
 * emits.
 * 
 * The pill is opened HERE, not by the calling frontend: DismissSession destroys
 * the overlay window that invoked this binding, so any JS after the await is
 * dead code — a recording with no Go-opened pill would be unstoppable.
 */
export function StartRecording(req: capture$0.CaptureRequest): $CancellablePromise<string> {
    return $Call.ByID(3056857500, req);
}

/**
 * StopRecording finalizes a recording and broadcasts capture:done.
 */
export function StopRecording(handleID: string): $CancellablePromise<capture$0.CaptureResult> {
    return $Call.ByID(1557301730, handleID).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MonitorSession.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = capture$0.CaptureResult.createFrom;
const $$createType3 = capture$0.ScreenInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
