// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound export API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CopyToClipboard copies the file at path to the system clipboard.
 * 
 *   - mediaType "image": publishes the PNG as a multi-format image bitmap so it
 *     pastes correctly (incl. transparency) into modern AND legacy targets.
 *   - mediaType "video": publishes the file as a CF_HDROP file-drop reference so
 *     it pastes into Explorer / Discord / Slack / Teams. (Windows has no
 *     universal "video bitstream on the clipboard" format; the file IS the payload.)
 */
export function CopyToClipboard(path: string, mediaType: string): $CancellablePromise<void> {
    return $Call.ByID(10702351, path, mediaType);
}

/**
 * ReadClipboardImage returns a base64 data URL of an image currently on the
 * clipboard, for the editor's "paste image as a layer" feature (toolbar-button
 * fallback; the in-webview JS `paste` event is the primary path).
 */
export function ReadClipboardImage(): $CancellablePromise<string> {
    return $Call.ByID(2251982236);
}

/**
 * SaveAs opens a native Save-As dialog seeded with suggestedName and copies
 * srcPath to the chosen destination. Used by BOTH editors. Returns the chosen
 * path, or an empty string if the user cancelled.
 */
export function SaveAs(srcPath: string, suggestedName: string): $CancellablePromise<string> {
    return $Call.ByID(3710390146, srcPath, suggestedName);
}
