// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateInfo describes an available update (returned to the frontend).
 */
export class UpdateInfo {
    /**
     * e.g. "1.3.0" (tag without leading v)
     */
    "version": string;

    /**
     * release body (markdown)
     */
    "notes": string;

    /**
     * browser_download_url of the installer
     */
    "assetUrl": string;

    /**
     * installer filename
     */
    "assetName": string;

    /**
     * expected hash from SHA256SUMS ("" if absent)
     */
    "sha256": string;

    /**
     * ISO-8601
     */
    "publishedAt": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("assetUrl" in $$source)) {
            this["assetUrl"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
