// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService is the Wails-bound updater API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate returns the available update, or nil if the app is up to date
 * (or running a "dev" build, which never reports updates).
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3232113843).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadAndInstall downloads the installer, verifies its SHA256 (if known),
 * launches it silently, and quits the app so toru.exe is unlocked for overwrite.
 */
export function DownloadAndInstall(info: $models.UpdateInfo): $CancellablePromise<void> {
    return $Call.ByID(2125856281, info);
}

/**
 * GetVersion returns the running version string.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2044035233);
}

/**
 * SetApp injects the running app (used to quit before the installer runs).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1999314030, app);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
