// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info is what the share card shows: the address to open on another device,
 * a QR code of that address, and which transport is running.
 */
export class Info {
    "url": string;
    "urls": string[];
    "port": number;
    "kind": string;
    "qrPng": string;
    "hint": string;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("urls" in $$source)) {
            this["urls"] = [];
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("qrPng" in $$source)) {
            this["qrPng"] = "";
        }
        if (!("hint" in $$source)) {
            this["hint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField1_0($$parsedSource["urls"]);
        }
        return new Info($$parsedSource as Partial<Info>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
