// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService is the Wails-bound history API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add copies srcPath into the library folder and prepends it to the recent list.
 * Used by the editor Done path (annotated PNG) and any other frontend import.
 * kind is "image" or "video".
 */
export function Add(srcPath: string, kind: string): $CancellablePromise<$models.Item> {
    return $Call.ByID(4179911378, srcPath, kind).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Delete removes one capture from the list and deletes its file.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2168179124, id);
}

/**
 * GetDir returns the absolute path of the library folder (empty if unset).
 */
export function GetDir(): $CancellablePromise<string> {
    return $Call.ByID(2434924928);
}

/**
 * IsDefaultDir reports whether the library uses the built-in default path.
 */
export function IsDefaultDir(): $CancellablePromise<boolean> {
    return $Call.ByID(2604347107);
}

/**
 * List returns recent captures newest-first (may be empty, never nil).
 */
export function List(): $CancellablePromise<$models.Item[]> {
    return $Call.ByID(351740431).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Open re-opens a capture by id: screenshots in the annotation editor,
 * recordings in the trim editor.
 */
export function Open(id: string): $CancellablePromise<void> {
    return $Call.ByID(2331004619, id);
}

/**
 * OpenFolder reveals the library directory in the OS file manager.
 */
export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(2936296111);
}

/**
 * PickDir opens a native folder picker and, if the user chooses a path, switches
 * the library there. Returns the new absolute path, or "" if the user cancelled.
 */
export function PickDir(): $CancellablePromise<string> {
    return $Call.ByID(820868001);
}

/**
 * ResetDir restores the built-in default library folder.
 */
export function ResetDir(): $CancellablePromise<void> {
    return $Call.ByID(2167278397);
}

/**
 * SetDir switches the library folder (creates it if needed) and reloads the list.
 */
export function SetDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(446929228, path);
}

// Private type creation functions
const $$createType0 = $models.Item.createFrom;
const $$createType1 = $Create.Array($$createType0);
