// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService is the Wails-bound history API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete removes one capture from the list and deletes its file.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2168179124, id);
}

/**
 * List returns recent captures newest-first (may be empty, never nil).
 */
export function List(): $CancellablePromise<$models.Item[]> {
    return $Call.ByID(351740431).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Open re-opens a capture by id: screenshots in the annotation editor,
 * recordings in the trim editor.
 */
export function Open(id: string): $CancellablePromise<void> {
    return $Call.ByID(2331004619, id);
}

/**
 * OpenFolder reveals the captures directory in the OS file manager.
 */
export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(2936296111);
}

// Private type creation functions
const $$createType0 = $models.Item.createFrom;
const $$createType1 = $Create.Array($$createType0);
