// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Item is one recent capture shown in the tray menu.
 */
export class Item {
    "id": string;

    /**
     * KindImage | KindVideo
     */
    "kind": string;

    /**
     * absolute path under captures/
     */
    "path": string;
    "label": string;
    "takenAt": time$0.Time;

    /** Creates a new Item instance. */
    constructor($$source: Partial<Item> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("takenAt" in $$source)) {
            this["takenAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     */
    static createFrom($$source: any = {}): Item {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item($$parsedSource as Partial<Item>);
    }
}
