// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AudioConfig is the user's audio-source selection. EVERY field is an
 * explicit opt-in; the zero value records NO audio whatsoever.
 */
export class AudioConfig {
    /**
     * whole system mix ("what you hear")
     */
    "system": boolean;

    /**
     * capture ONLY these process trees
     */
    "appPids": number[];

    /**
     * dshow device name; "" = no mic
     */
    "micDevice": string;

    /** Creates a new AudioConfig instance. */
    constructor($$source: Partial<AudioConfig> = {}) {
        if (!("system" in $$source)) {
            this["system"] = false;
        }
        if (!("appPids" in $$source)) {
            this["appPids"] = [];
        }
        if (!("micDevice" in $$source)) {
            this["micDevice"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AudioConfig {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appPids" in $$parsedSource) {
            $$parsedSource["appPids"] = $$createField1_0($$parsedSource["appPids"]);
        }
        return new AudioConfig($$parsedSource as Partial<AudioConfig>);
    }
}

/**
 * AudioSession is one application currently producing audio — a row in the
 * per-app capture picker.
 */
export class AudioSession {
    "pid": number;
    "name": string;

    /** Creates a new AudioSession instance. */
    constructor($$source: Partial<AudioSession> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioSession instance from a string or object.
     */
    static createFrom($$source: any = {}): AudioSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AudioSession($$parsedSource as Partial<AudioSession>);
    }
}

/**
 * CaptureRequest is what the overlay emits on commit. It is the entire input
 * to the shared Capture() seam.
 */
export class CaptureRequest {
    /**
     * "screenshot" | "video"
     */
    "mode": string;

    /**
     * "region" | "window" | "fullscreen"
     */
    "sub": string;

    /**
     * index; == ddagrab output_idx
     */
    "monitorId": number;

    /**
     * physical px, virtual-desktop origin
     */
    "rect": Rect;

    /**
     * scale factor of the owning monitor
     */
    "dpiScale": number;

    /**
     * draw_mouse / DXGI cursor compose
     */
    "includeCursor": boolean;

    /**
     * 0 | 5 | 10 (video only)
     */
    "countdownSec": number;

    /**
     * v1.1 audio
     */
    "micDevice"?: string;

    /**
     * copy to clipboard instead of save
     */
    "copyOnCommit": boolean;

    /** Creates a new CaptureRequest instance. */
    constructor($$source: Partial<CaptureRequest> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("sub" in $$source)) {
            this["sub"] = "";
        }
        if (!("monitorId" in $$source)) {
            this["monitorId"] = 0;
        }
        if (!("rect" in $$source)) {
            this["rect"] = (new Rect());
        }
        if (!("dpiScale" in $$source)) {
            this["dpiScale"] = 0;
        }
        if (!("includeCursor" in $$source)) {
            this["includeCursor"] = false;
        }
        if (!("countdownSec" in $$source)) {
            this["countdownSec"] = 0;
        }
        if (!("copyOnCommit" in $$source)) {
            this["copyOnCommit"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CaptureRequest {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rect" in $$parsedSource) {
            $$parsedSource["rect"] = $$createField3_0($$parsedSource["rect"]);
        }
        return new CaptureRequest($$parsedSource as Partial<CaptureRequest>);
    }
}

/**
 * CaptureResult is what Capture() returns and what the "capture:done" event
 * carries. The `Mode` field is what routes the result to Developer 1's editor
 * (screenshot) vs Developer 2's editor (video).
 */
export class CaptureResult {
    "mode": string;

    /**
     * set when Mode == "screenshot"
     */
    "imagePath"?: string;

    /**
     * set when Mode == "video" (on stop)
     */
    "videoPath"?: string;

    /**
     * long-lived recording handle
     */
    "handleId"?: string;
    "rect": Rect;
    "monitorId": number;
    "cancelled": boolean;

    /** Creates a new CaptureResult instance. */
    constructor($$source: Partial<CaptureResult> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("rect" in $$source)) {
            this["rect"] = (new Rect());
        }
        if (!("monitorId" in $$source)) {
            this["monitorId"] = 0;
        }
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CaptureResult {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rect" in $$parsedSource) {
            $$parsedSource["rect"] = $$createField4_0($$parsedSource["rect"]);
        }
        return new CaptureResult($$parsedSource as Partial<CaptureResult>);
    }
}

/**
 * Rect is ALWAYS in virtual-desktop PHYSICAL pixels.
 * 
 * Origin = primary-monitor top-left. Monitors positioned to the LEFT of or
 * ABOVE the primary monitor therefore have NEGATIVE X/Y.
 * 
 * Coordinate contract (THE single most important seam detail):
 *   - ffmpeg `gdigrab`  consumes X/Y DIRECTLY (its offset_x/offset_y are
 *     virtual-desktop coordinates; negatives are allowed). No conversion.
 *   - ffmpeg `ddagrab`  does NOT. Its offset_x/offset_y are MONITOR-RELATIVE
 *     and the monitor is selected by output_idx. The SAME Rect cannot feed
 *     both unchanged.
 * 
 * Therefore internal/capture/args.go is the SOLE owner of rebasing: for the
 * ddagrab path it sets output_idx = MonitorID and emits
 * offset_x = Rect.X - screen.X, offset_y = Rect.Y - screen.Y.
 */
export class Rect {
    "x": number;
    "y": number;
    "w": number;
    "h": number;

    /** Creates a new Rect instance. */
    constructor($$source: Partial<Rect> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            this["h"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rect instance from a string or object.
     */
    static createFrom($$source: any = {}): Rect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rect($$parsedSource as Partial<Rect>);
    }
}

/**
 * ScreenInfo describes one monitor. Overlay.ListScreens() is the SINGLE source
 * of truth for screen enumeration that both halves trust.
 */
export class ScreenInfo {
    /**
     * index; == ddagrab output_idx
     */
    "id": number;

    /**
     * physical px, virtual-desktop origin (may be negative)
     */
    "x": number;
    "y": number;
    "w": number;
    "h": number;
    "scaleFactor": number;
    "isPrimary": boolean;

    /** Creates a new ScreenInfo instance. */
    constructor($$source: Partial<ScreenInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            this["h"] = 0;
        }
        if (!("scaleFactor" in $$source)) {
            this["scaleFactor"] = 0;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ScreenInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenInfo($$parsedSource as Partial<ScreenInfo>);
    }
}

/**
 * WindowInfo describes a top-level app window that can be captured (screenshot
 * or video). Rect is virtual-desktop PHYSICAL px (same space as contract.Rect).
 */
export class WindowInfo {
    "hwnd": number;
    "title": string;
    "rect": Rect;
    /**
     * dominant monitor (kbinani idx); -1 if unknown
     */
    "monitorId": number;

    /** Creates a new WindowInfo instance. */
    constructor($$source: Partial<WindowInfo> = {}) {
        if (!("hwnd" in $$source)) {
            this["hwnd"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("rect" in $$source)) {
            this["rect"] = (new Rect());
        }
        if (!("monitorId" in $$source)) {
            this["monitorId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowInfo {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rect" in $$parsedSource) {
            $$parsedSource["rect"] = $$createField2_0($$parsedSource["rect"]);
        }
        return new WindowInfo($$parsedSource as Partial<WindowInfo>);
    }
}

/**
 * TrimRequest is Developer 2's input to the video trimmer.
 */
export class TrimRequest {
    "videoPath": string;
    "startMs": number;
    "endMs": number;

    /**
     * true = re-encode (frame-accurate); false = -c copy
     */
    "precise": boolean;
    "outPath": string;

    /** Creates a new TrimRequest instance. */
    constructor($$source: Partial<TrimRequest> = {}) {
        if (!("videoPath" in $$source)) {
            this["videoPath"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("precise" in $$source)) {
            this["precise"] = false;
        }
        if (!("outPath" in $$source)) {
            this["outPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrimRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TrimRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrimRequest($$parsedSource as Partial<TrimRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Rect.createFrom;
