// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as SettingsService from "./settingsservice.js";
import * as WindowsService from "./windowsservice.js";
export {
    SettingsService,
    WindowsService
};
