// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the Wails-bound API for app-level preferences that aren't
 * keyboard shortcuts. Right now that's just "launch at Windows login", backed
 * directly by Wails' AutostartManager — on Windows the registry Run key IS the
 * source of truth, so there is nothing extra to persist in settings.json.
 * 
 * JS binding name: SettingsService.*
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetLaunchAtLogin reports whether Toru is currently registered to start at user
 * login. It reads the live registry state via Wails' AutostartManager, so it
 * reflects reality even if the entry was added/removed outside the app.
 */
export function GetLaunchAtLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(1992032939);
}

/**
 * SetLaunchAtLogin enables or disables launch-at-login. When enabling, Toru is
 * registered WITH the --startup argument so the login launch starts silently in
 * the tray (no Settings window — see startupArg). Disabling removes the registry
 * entry. Re-enabling is safe: Wails overwrites the existing value.
 */
export function SetLaunchAtLogin(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1701942847, enabled);
}
