// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowsService opens Toru's separate windows (overlay, screenshot editor,
 * trim editor). Each window loads a distinct frontend route. This is the
 * multi-window backbone that lets Developer 1 and Developer 2 own independent
 * windows. (JS binding name: WindowsService.*)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CloseRecordingFrame tears down the recorded-region border window if one is up.
 */
export function CloseRecordingFrame(): $CancellablePromise<void> {
    return $Call.ByID(396899040);
}

/**
 * OpenEditor opens Developer 1's screenshot annotation editor for imagePath.
 * 
 * The SPA routes on the ?view= query param (App.tsx) and the embedded asset
 * server has no /editor path, so the window URL MUST be /?view=editor (a bare
 * /editor 404s). The webview also can't load a raw C:\ path as <img src>, so the
 * committed PNG is handed over as the /__file/<basename> served URL.
 */
export function OpenEditor(imagePath: string): $CancellablePromise<void> {
    return $Call.ByID(642594709, imagePath);
}

/**
 * OpenOverlay opens the shared dim/crop capture overlay session: one frameless,
 * always-on-top, opaque window per monitor showing a FROZEN still dimmed with a
 * crop hole. Delegates to OverlayService.BeginSession, which freezes every
 * monitor BEFORE any window is shown. This is the launch + hotkey + tray
 * entrypoint.
 */
export function OpenOverlay(): $CancellablePromise<void> {
    return $Call.ByID(4149419780);
}

/**
 * OpenRecordingControls opens the small frameless always-on-top "recording
 * pill" (timer + Stop) for an in-flight recording. The overlay service calls
 * this from Go right after StartRecording — without it a recording has NO
 * stop affordance (the tray Stop square is still a Phase-0 stub).
 * 
 * Placement: top-center of a monitor that is NOT being recorded when one
 * exists (so the pill never appears inside a fullscreen recording); otherwise
 * top-center of the recorded monitor's work area — same trade-off Loom makes.
 */
export function OpenRecordingControls(handleID: string, monitorID: number): $CancellablePromise<void> {
    return $Call.ByID(4141771617, handleID, monitorID);
}

/**
 * OpenRecordingError surfaces a FAILED StartRecording as a small dismissible pill.
 * The overlay is already hidden by the time ffmpeg reports it can't capture, so
 * without this the user is left with a blank screen and no idea why nothing
 * recorded. Same frameless placement as the live pill; the recording route renders
 * the error state off the ?startError= param.
 */
export function OpenRecordingError(message: string, monitorID: number): $CancellablePromise<void> {
    return $Call.ByID(846290679, message, monitorID);
}

/**
 * OpenRecordingFrame opens the "glowing border" window that outlines the recorded
 * region while recording. The overlay passes the EXACT region DIP bounds; we
 * expand by recFrameMargin on every side and hand the margin to React, which draws
 * the animated outline within that band — OUTSIDE the recorded rect, so ffmpeg
 * never captures it.
 * 
 * The window is TRANSPARENT + click-through (IgnoreMouseEvents): every pixel,
 * including the outline band, passes mouse input through to whatever is being
 * recorded, so the indicator never steals a click. Singleton: a stale frame from a
 * previous recording is closed first.
 */
export function OpenRecordingFrame(dipX: number, dipY: number, dipW: number, dipH: number, monitorID: number): $CancellablePromise<void> {
    return $Call.ByID(3001338060, dipX, dipY, dipW, dipH, monitorID);
}

/**
 * OpenSettings opens Toru's Settings/home window: the tray-driven hub that hosts
 * the Shortcuts panel, the updater/about, and a Capture button. Reached from the
 * tray menu, the tray left-click, the ApplicationStarted launch, and the editor's
 * floating gear button.
 * 
 * SINGLETON: the Settings window is the app's persistent home, hit repeatedly from
 * the tray. If one is already open this Show().Focus()es it (restoring it first if
 * minimised) instead of spawning a duplicate frameless window — without this, every
 * tray click would stack another window that DisableQuitOnLastWindowClosed then
 * keeps alive forever, reintroducing the exact multi-window confusion this redesign
 * removed. The handle is cleared when the window closes.
 */
export function OpenSettings(): $CancellablePromise<void> {
    return $Call.ByID(489256705);
}

/**
 * OpenTrim opens Developer 2's trim editor for videoPath. Same routing + served-
 * file rules as OpenEditor (/?view=trim, /__file/<basename> for the media src).
 * The raw absolute path rides along as ?path= — the webview needs the served
 * URL to PLAY the file, but Copy/Save-As/Trim are Go-side operations on the
 * real path, which cannot be reconstructed from the served URL.
 */
export function OpenTrim(videoPath: string): $CancellablePromise<void> {
    return $Call.ByID(1119648552, videoPath);
}
