// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowsService opens Toru's separate windows (overlay, screenshot editor,
 * trim editor). Each window loads a distinct frontend route. This is the
 * multi-window backbone that lets Developer 1 and Developer 2 own independent
 * windows. (JS binding name: WindowsService.*)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/capture/models.js";

/**
 * OpenEditor opens Developer 1's screenshot annotation editor for imagePath.
 */
export function OpenEditor(imagePath: string): $CancellablePromise<void> {
    return $Call.ByID(642594709, imagePath);
}

/**
 * OpenHub opens the dev Hub window (buttons to drive both editors during Phase
 * 0). Cancel/Esc on the overlay returns here.
 */
export function OpenHub(): $CancellablePromise<void> {
    return $Call.ByID(3348539563);
}

/**
 * OpenOverlay opens the shared dim/crop capture overlay session: one frameless,
 * always-on-top, opaque window per monitor showing a FROZEN still dimmed with a
 * crop hole. Delegates to OverlayService.BeginSession, which freezes every
 * monitor BEFORE any window is shown. This is the launch + hotkey + tray
 * entrypoint.
 */
export function OpenOverlay(): $CancellablePromise<void> {
    return $Call.ByID(4149419780);
}

/**
 * OpenTrim opens Developer 2's trim editor for videoPath.
 */
export function OpenTrim(videoPath: string): $CancellablePromise<void> {
    return $Call.ByID(1119648552, videoPath);
}

/**
 * SimulateCapture runs the (stubbed) capture seam for the given mode and opens
 * the matching editor window. This is the dev-hub shortcut that exercises the
 * whole path — capture -> CaptureResult -> route-by-mode -> editor window —
 * before global hotkeys + the real overlay are wired.
 */
export function SimulateCapture(mode: string): $CancellablePromise<capture$0.CaptureResult> {
    return $Call.ByID(1982809100, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = capture$0.CaptureResult.createFrom;
