// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound video API (Developer 2).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "../capture/models.js";

/**
 * ExportForDiscord re-encodes videoPath to fit Discord's 10MB free-tier cap
 * using two-pass VP9 targeting ~9MB, with the bitrate computed from the
 * clip's real duration. Sources already under the target are returned as-is
 * (sharing the original beats a pointless re-encode).
 */
export function ExportForDiscord(videoPath: string): $CancellablePromise<string> {
    return $Call.ByID(4223502624, videoPath);
}

/**
 * GenerateThumbnails extracts `count` evenly-spaced frames for the trim
 * filmstrip and returns their file paths.
 * 
 * TODO(dev2): compute timestamps from duration (ffprobe) and emit a tiled
 * filmstrip; this stub wires the resolver + output dir only.
 */
export function GenerateThumbnails(videoPath: string, count: number): $CancellablePromise<string[]> {
    return $Call.ByID(2651258301, videoPath, count).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Trim cuts [StartMs, EndMs] from req.VideoPath into req.OutPath. Precise=false
 * is a fast stream-copy (snaps to nearest preceding keyframe); Precise=true
 * re-encodes for frame accuracy.
 */
export function Trim(req: capture$0.TrimRequest): $CancellablePromise<string> {
    return $Call.ByID(3139144495, req);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
